### ISSUE TITLE
大佬，有没有办法在文档的页数等基本信息啊

### ISSUE THREAD

**Issue by chengked** [wytxer/demo-onlyoffice#1]
我想在外面拿到文档的页数等基本信息，但是看了那么多文档，好像没办法实现，请问大佬您有没有遇到这样的使用场景

**Comment by wytxer** [comment]
没遇到过。你这个具体需要文档的哪些信息呢？让后端支持一下？

**Comment by chengked** [comment]
> 没遇到过。你这个具体需要文档的哪些信息呢？让后端支持一下？

后面想了个方案，改它前端web-apps，增加api调用前端面板的方法。

**Comment by chengked** [comment]
> 



> > 没遇到过。你这个具体需要文档的哪些信息呢？让后端支持一下？
> 
> 后面想了个方案，改它前端web-apps，增加api调用前端面板的方法。

已经实现了，可行
