### ISSUE TITLE
onlyoffice 入口文件加载失败，不知什么原因

### ISSUE THREAD

**Issue by adward321** [wytxer/demo-onlyoffice#2]
![image](https://user-images.githubusercontent.com/26714176/202124934-9e30d2f2-285d-4f5a-a1fb-407a5e81898f.png)
应该是跨域问题，不知楼主那是否有，我看 server 中有做 cors 处理，不知楼主怎么解决的

**Comment by wytxer** [comment]
我没遇到过，直接浏览器打开能访问这个 js 吗？

**Comment by weekyuan** [comment]
我也遇到这个问题，主要是8701端口没有启动导致的，请问8701端口怎么启动？

**Comment by wytxer** [comment]
启动 onlyoffice docker 时指定的端口号，细节你可以看下这篇文章：https://juejin.cn/post/7136223880657502238 @weekyuan

**Comment by gangya0327** [comment]
@wytxer 大大，我也遇到上面的问题了，用pnpm安装完以后，pnpm run dev启动，终端已经提示启动成功，但打不开8701端口下的内容，提示已拒绝连接，访问3000端口是可以的

**Comment by wytxer** [comment]
@gangya0327 onlyoffice docker 启动了吗

**Comment by wytxer** [comment]
时间久远，这个先关了，有问题新开一个 issues 哈
