### ISSUE TITLE
The document security token is not correctly formed.

### ISSUE THREAD

**Issue by wu529778790** [wytxer/demo-onlyoffice#3]
The document security token is not correctly formed.
Please contact your Document Server administrator.

{
    "message": "not authorized",
    "data": {
        "code": 4006,
        "description": "token:jwt must be provided"
    }
}

打开文件提示没有权限，但是秘钥也是新生成的，感觉是ip配置没有配置好

我的docker是装在服务器上的

**Comment by wu529778790** [comment]
修改的配置主要是这两个：其他没动
![image](https://user-images.githubusercontent.com/11481938/230880183-0e5c3a28-6c59-4bf2-aeab-161352aea47b.png)
![image](https://user-images.githubusercontent.com/11481938/230880236-3b62b168-d1b9-432d-ab72-6b7bbd37512f.png)

**Comment by wu529778790** [comment]
![image](https://user-images.githubusercontent.com/11481938/230880693-307f855e-3d90-4c64-a49d-763399f2d26b.png)

**Comment by wu529778790** [comment]
![image](https://user-images.githubusercontent.com/11481938/230884469-9066702a-8206-49f6-9e52-3a366df11659.png)

**Comment by wytxer** [comment]
安装的 onlyoffice 版本号是？JWT 配置改动后是否重启过 onlyoffice docker 服务？

**Comment by wu529778790** [comment]
> 安装的 onlyoffice 版本号是？JWT 配置改动后是否重启过 onlyoffice docker 服务？

![image](https://user-images.githubusercontent.com/11481938/231105391-2ded0ca6-3894-41f4-a0a9-774bb23773ae.png)
