### ISSUE TITLE
所有都启动后 访问提示令牌问题

### ISSUE THREAD

**Issue by Mrtaochen** [wytxer/demo-onlyoffice#5]
![image](https://github.com/wytxer/demo-onlyoffice/assets/23125140/a2f68b1a-af69-4d60-9637-82d7024145fa)

**Comment by Mrtaochen** [comment]
大佬有遇到这个么，
<img width="1093" alt="image" src="https://github.com/wytxer/demo-onlyoffice/assets/23125140/5799cd27-0932-431a-b874-a2f500dab553">
这里token改为false,也没有用

**Comment by wytxer** [comment]
提供的信息不多，以下是一些建议：
1、demo-onlyoffice 是否关闭了 JWT
2、onlyoffice docker local.json 修改后的配置是什么样的？修改完成后是否重启了 onlyoffice docker 服务？
3、清除浏览器缓存

**Comment by wytxer** [comment]
时间久远，这个先关了，有问题新开一个 issues 哈
