### ISSUE TITLE
为什么我写的后端会出现downloadfailed,有什么要注意的吗

### ISSUE THREAD

**Issue by theBig-brother** [wytxer/demo-onlyoffice#7]

**Comment by wytxer** [comment]
文章与仓库代码是一体的，强烈建议跟着文章步骤运行例子。

- [在 Vue 中接入 Onlyoffice](https://bszhct.com/2022/08/15/onlyoffice-quick-start/)
- [Onlyoffice 二次开发指南，包含自定义 Onlyoffice 配置、使用 JWT 加密 Onlyoffice 配置、Onlyoffice 文档转换等](https://bszhct.com/2022/08/19/onlyoffice-usage/)

@theBig-brother
