### ISSUE TITLE
后端模块的作用

### ISSUE THREAD

**Issue by fuuhoo** [wytxer/demo-onlyoffice#8]
这个项目后端模块的作用是什么，和docker的服务之间的关系是什么

**Comment by wytxer** [comment]
![image](https://github.com/wytxer/demo-onlyoffice/assets/96920091/f535166b-5885-4cb0-af60-8cacf00134d6)

具体可在这篇文章中查看：https://bszhct.com/2022/08/19/onlyoffice-usage/

@fuuhoo
